name: CI & CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker compose build 
    - name: Push to Dockerhub
      run: docker compose push

  deploy:

    runs-on: self-hosted
    needs: build

    steps:
    - name: Delete Old docker container
      run: sudo docker rm -f zenova-api || true
    
    - name: Delete Old docker Image
      run:  sudo docker rmi -f moinaknaskar/zenova:latest || true

    - name: Reset docker history
      run:  sudo docker system prune -f || true
    - name: Pull Docker image
      run: sudo docker pull moinaknaskar/zenova:latest
    - name: Delete Old docker container
      run: sudo docker rm -f zenova-api || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8000:8000 --name zenova-api moinaknaskar/zenova
